apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: codegen-oct22-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/codegen-oct22-1:fe8f26d8765ba4df5822ac493db4d4c4a21dff03@sha256:17817639a6a1832a886e7d5a7b7eefa07051519d6d0a9a3286cd26469d9fb1a0 # use pre-built to bootstrap 
          name: app-inference
